### ISSUE TITLE
При выполнении операции пополнения (add) сберегательного счёта (SavingAccount) баланс счёта меняется с начального баланса (initialBalance) на сумму пополнения (amount)

### ISSUE THREAD

**Issue by lollygolly** [ElzaRadikovna/javaqa-team-diplom#1]
**#Описание**

При выполнении операции пополнения (add) счёта (SavingAccount) на сумму (amount) 3_000 при начальном балансе счёта (initialBalance) в 2_000 баланс счёта изменяется на 3_000.

**#Локация дефекта**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/6258870820b32b1661549f97e91ea05e40ab3339/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L73

**#Шаги воспроизведения**

**1.** Открыть код программы https://github.com/ElzaRadikovna/javaqa-team-diplom/tree/main/src/main/java/ru/netology/javaqadiplom в IDEA

**2.** Создать новый объект сберегательного счёта с параметрами: 

- initialBalance  (начальный баланс): 2_000,
- minBalance (минимальный баланс): 1_000,
- maxBalance (максимальный баланс): 10_000,
- rate (ставка в процентах годовых на остаток): 5

**3.** Вызвать метод пополнения карты (add) на указанную сумму (amount) - 3_000

**4.** Сделать Assertions ожидаемого и фактического результатов, где ожидаемый результат - сумма начального баланса счёта и суммы пополнения (2_000 + 3_000), а фактический результат - вызов метода .getBalance

**5.** Запустить проверку теста командой mvn cleam verify в консоле IDEA

**Фактический результат:** 
Тест провален с сообщением "expected: <5000> but was: <3000>"

**Ожидаемый результат:**
Тест пройден успешно

**Тест для проверки:**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/e5c5eca3b36c243ca3c102e92f9abd762dc4f1ac/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

**#Скриншот**

![Скриншот интерфейса IDEA с багом](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/148256844/333ffd5a-5549-4a96-8e78-aa3657a318d2)

**#Окружение**

- Операционная система: Windows 10 22H2
- IDEA: IntelliJ IDEA Community Edition 2023.2.4
- Java: corretto-11 11.0.21

**Comment by ElzaRadikovna** [comment]
Дефект исправлен
