### ISSUE TITLE
Рассчитывается процентная ставка на положительный баланс счета

### ISSUE THREAD

**Issue by ElzaRadikovna** [ElzaRadikovna/javaqa-team-diplom#10]
# Описание
Совершается операция расчёта процентов на положительный баланс счёта, когда по условию при любой ставке ответ должен быть 0.
# Локация дефекта
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/6258870820b32b1661549f97e91ea05e40ab3339/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java)
2. Создать объект класса CreditAccount
3. Вставить значение переменной "initialBalance" (начальный баланс) в 2000руб.
4. Вставить значение переменной "creditLimit" (кредитный лимит) в 5000руб.
5. Вставить значение переменной "rate" (ставка кредитования) в 15%
6. Рассчитать проценты , используя Assertions.assertEquals(expected 0, account.yearChange()) для сравнения результатов.

*Ожидаемый результат:* Процентная ставка равна нулю.
*Фактический результат:* Процентная ставка равна 300.
# Локация теста, для проверки метода
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/c70e19b6fd5fb785c7b32a4c9e73b681ad9adaca/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L107
# Скриншот
![Скриншот 17-01-2024 153528](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/147627129/365ca2e8-0098-4d1e-b594-62bab797686b)

# Окружение
* Операционная система: Windows 10
* IDEA: IntellieJ IDEA 2023.2.4 (Ultimate Edition)
* Java: Open JDK11

**Comment by lollygolly** [comment]
conditions for yearChange method were added, formula was changed
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/d526d395035d297daa4c0e2488e15ed77e5a6b58/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L97
