### ISSUE TITLE
Совершается покупка на сумму, превышающую кредитный лимит

### ISSUE THREAD

**Issue by ElzaRadikovna** [ElzaRadikovna/javaqa-team-diplom#11]
# Описание
При совершении операции покупки (pay) на сумму, превышающую кредитный лимит (creditLimit), сумма баланса становится отрицательной, когда по условию операция должна завершиться, вернув false и ничего не поменяв на счёте.
# Локация дефекта
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/c70e19b6fd5fb785c7b32a4c9e73b681ad9adaca/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java)
2. Создать объект класса CreditAccount
3. Вставить значение переменной "initialBalance" (начальный баланс) в 2000руб.
4. Вставить значение переменной "creditLimit" (кредитный лимит) в 5000руб.
5. Вставить значение переменной "rate" (ставка кредитования) в 15%
6. Совершить покупку на сумму "ammount" 6000руб. методом pay
7. Использовать Assertions.assertEquals (expected 5000, actual account.getBalance()) для сравнения результатов.

*Ожидаемый результат:* операция завершилась, вернув false и ничего не поменяв на счёте(5000).
*Фактический результат:* покупка совершилась, баланс стал отрицательным (-6000).
# Локация теста, для проверки метода
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/c70e19b6fd5fb785c7b32a4c9e73b681ad9adaca/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L91
# Скриншот
![Скриншот 17-01-2024 160434](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/147627129/4571969f-3adc-4be5-a89f-b205a3958bcc)

# Окружение
* Операционная система: Windows 10
* IDEA: IntellieJ IDEA 2023.2.4 (Ultimate Edition)
* Java: Open JDK11

**Comment by lollygolly** [comment]
При initialBalance 2000 и creditLimit в 5000, если мы совершаем покупку (pay) на 6000, то у нас останется на счете 2000-6000=-4000, а это не превышает лимит в 5000 рублей.
Для случаев, когда balance-amount < -creditLimit были добавлены условия в код
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/20bd3c4007adbe0f233d6d158a6cd95d96029fbd/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L57
