### ISSUE TITLE
При выполнении платежа (pay), когда платеж (amount) больше баланса (balance), не срабатывает ранний выход и выполнение метода приводит с отрицательному балансу

### ISSUE THREAD

**Issue by lollygolly** [ElzaRadikovna/javaqa-team-diplom#12]
**#Описание**

При выполнении функции платежа (pay), когда платеж (amount) превышает баланс на счёте (balance), не выполняется ранний выход и выполнение функции приводит к отрицательному балансу на счёте

**#Локация дефекта**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/65c1f33a47f01651a403a57bdb227e12c3b1c9e9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L49

**#Шаги воспроизведения**

**1.** Открыть код программы https://github.com/ElzaRadikovna/javaqa-team-diplom/tree/main/src/main/java/ru/netology/javaqadiplom в IDEA

**2.** Создать объект класса SavingAccount со следующими параметрами:

- initialBalance (начальный баланс): 2_000,
- minBalance (минимальный баланс): 1_000,
- maxBalance (максимальный баланс): 10_000,
- rate (ставка в процентах годовых на остаток): 10

**3.** Вызвать метод pay с параметром account=3_000 (> balance)

**4.** Запустить ассерт ожидаемого баланса - 2_000 (баланс не должен измениться) и функции get.balance()

**Фактический результат:**
Тест провален с сообщением "org.opentest4j.AssertionFailedError: 
Expected :2000
Actual   :-1000"

**Ожидаемый результат:**
Тест пройден успешно

**#Тест для проверки:**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/65c1f33a47f01651a403a57bdb227e12c3b1c9e9/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L160

**#Скриншот**

![Скриншот экрана IDEA с ошибкой в терминале](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/148256844/ffdca870-7f69-4b03-b406-bdd929ef8e72)

**#Окружение**

- Операционная система: Windows 10 22H2
- IDEA: IntelliJ IDEA Community Edition 2023.2.4
- Java: corretto-11 11.0.21

**Comment by ElzaRadikovna** [comment]
Дефект исправлен
