### ISSUE TITLE
При выполнении метода pay, когда после платежа (amount) баланс (balance) становится меньше минимального значения (minBalance), не срабатывает ранний выход

### ISSUE THREAD

**Issue by lollygolly** [ElzaRadikovna/javaqa-team-diplom#13]
**#Описание**

При выполнении функции платежа (pay), когда платеж (amount) не превышает баланс на счёте (balance), но выполнение платежа приводит к некорректным значениям баланса (баланс становится меньше минимального значения (minBalance)), не выполняется ранний выход и значение баланса изменяется

**#Локация дефекта**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/65c1f33a47f01651a403a57bdb227e12c3b1c9e9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L49

**#Шаги воспроизведения**

**1.** Открыть код программы https://github.com/ElzaRadikovna/javaqa-team-diplom/tree/main/src/main/java/ru/netology/javaqadiplom в IDEA

**2.** Создать объект класса SavingAccount со следующими параметрами:

- initialBalance (начальный баланс): 2_000,
- minBalance (минимальный баланс): 1_000,
- maxBalance (максимальный баланс): 10_000,
- rate (ставка в процентах годовых на остаток): 10

**3.** Вызвать метод pay с параметром account=1_500 (> balance)

**4.** Запустить ассерт ожидаемого баланса - 2_000 (баланс не должен измениться) и функции get.balance()

**Фактический результат:**
Тест провален с сообщением "org.opentest4j.AssertionFailedError: 
Expected :2000
Actual   :500"

**Ожидаемый результат:**
Тест пройден успешно

**#Тест для проверки:**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/cd969267c45f315dbccd534379a1de3617d797ed/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L174

**#Скриншот**

![Скриншот экрана IDEA с ошибкой в терминале](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/148256844/a63105e9-6528-477d-b608-a719460bd952)

**#Окружение**

- Операционная система: Windows 10 22H2
- IDEA: IntelliJ IDEA Community Edition 2023.2.4
- Java: corretto-11 11.0.21

**Comment by ElzaRadikovna** [comment]
Дефект исправлен
