### ISSUE TITLE
При выполнении функции пополнения счёта (add), когда баланс (balance) должен стать равным максимальному значению (maxBalance), баланс не изменяется

### ISSUE THREAD

**Issue by lollygolly** [ElzaRadikovna/javaqa-team-diplom#14]
**#Описание**

При выполнении функции пополнения счёта (add) на сумму (amount), при которой баланс (balance) должен стать равным значению максимального баланса (maxBalance), функция не срабатывает, значение баланса остается прежним

**#Локация дефекта**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/65c1f33a47f01651a403a57bdb227e12c3b1c9e9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L73

**#Шаги воспроизведения**

**1.** Открыть код программы https://github.com/ElzaRadikovna/javaqa-team-diplom/tree/main/src/main/java/ru/netology/javaqadiplom в IDEA

**2.** Создать объект класса SavingAccount со следующими параметрами:

- initialBalance (начальный баланс): 2_000,
- minBalance (минимальный баланс): 1_000,
- maxBalance (максимальный баланс): 10_000,
- rate (ставка в процентах годовых на остаток): 10

**3.** Вызвать метод add с параметром account=8_000;

**4.** Запустить ассерт ожидаемого баланса - 10_000 (баланс должен увеличиться на 8_000) и функции get.balance()

**Фактический результат:**
Тест провален с сообщением "org.opentest4j.AssertionFailedError: 
Expected :10000
Actual   :2000"

**Ожидаемый результат:**
Тест пройден успешно

**#Тест для проверки:**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/bb8735f1febb9e88e370daaae825bc296bce6892/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L218

**#Скриншот**

![Скриншот экрана IDEA с ошибкой в терминале](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/148256844/09cf0c5a-7e15-40b2-aba1-305e21a4de0b)

**#Окружение**

- Операционная система: Windows 10 22H2
- IDEA: IntelliJ IDEA Community Edition 2023.2.4
- Java: corretto-11 11.0.21

**Comment by ElzaRadikovna** [comment]
Дефект исправлен
