### ISSUE TITLE
Функция расчёта процентов на остаток счёта (yearChange) округляет значение баланса до расчета процентов

### ISSUE THREAD

**Issue by lollygolly** [ElzaRadikovna/javaqa-team-diplom#15]
**#Описание**

При выполнении функции расчёта процентов на остаток счета (yearChange), когда баланс (balance) не делиться нацело на 100, функция округляет значение баланса до умножения на процентную ставку (rate), что приводит к ошибкам

**#Локация дефекта**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/fb5d8f796f0f6258a3ed418a57fd6339f2374a99/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L89

**#Шаги воспроизведения**

**1.** Открыть код программы https://github.com/ElzaRadikovna/javaqa-team-diplom/tree/main/src/main/java/ru/netology/javaqadiplom в IDEA

**2.** Создать объект класса SavingAccount со следующими параметрами:

- initialBalance (начальный баланс): 250,
- minBalance (минимальный баланс): 100,
- maxBalance (максимальный баланс): 100_000,
- rate (ставка в процентах годовых на остаток): 15

**3.** Создать переменную percent и вызвать для нее метод yearChange;

**4.** Запустить ассерт ожидаемого значения процентов - 37 (250*0,15=37,5) и значения percent;

**Фактический результат:**
Тест провален с сообщением "org.opentest4j.AssertionFailedError: 
Expected :37
Actual   :30"

**Ожидаемый результат:**
Тест пройден успешно

**#Тест для проверки:**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/fb5d8f796f0f6258a3ed418a57fd6339f2374a99/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L290

**#Скриншот**

![Скриншот экрана IDEA с ошибкой в терминале](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/148256844/1e2b5f43-b9e8-40cb-b8d9-27af34549581)

**#Окружение**

- Операционная система: Windows 10 22H2
- IDEA: IntelliJ IDEA Community Edition 2023.2.4
- Java: corretto-11 11.0.21

**Comment by ElzaRadikovna** [comment]
Дефект исправлен
