### ISSUE TITLE
При расчете годового процента (yearChange) на отрицательный баланс, целочисленное деление работает некорректно

### ISSUE THREAD

**Issue by ElzaRadikovna** [ElzaRadikovna/javaqa-team-diplom#16]
# Описание
При расчете годового процента (yearChange) на отрицательный баланс, если процентная ставка - дробное число, то целочисленное деление работает некорректно. (при балансе -170, процентной ставке 15%, годовой процент должен быть равен -25. А программа выдает -15)
# Локация дефекта
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/c70e19b6fd5fb785c7b32a4c9e73b681ad9adaca/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L83
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java)
2. Создать объект класса CreditAccount
3. Вставить значение переменной "initialBalance" (начальный баланс) в -170руб.
4. Вставить значение переменной "creditLimit" (кредитный лимит) в 5000руб.
5. Вставить значение переменной "rate" (ставка кредитования) в 15%
6. Используя Assertions.assertEquals(expected -25, account.yearChange()), сравнить результаты.

*Ожидаемый результат:* Годовая ставка равна -25%
*Фактический результат:* Годовая ставка равно -15%

# Локация теста, для проверки метода
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/c70e19b6fd5fb785c7b32a4c9e73b681ad9adaca/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L118
# Скриншот
![Скриншот 18-01-2024 225115](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/147627129/8b5adf8f-f589-461f-a998-cae52cec6b54)

# Окружение
* Операционная система: Windows 10
* IDEA: IntellieJ IDEA 2023.2.4 (Ultimate Edition)
* Java: Open JDK11

**Comment by lollygolly** [comment]
По условиям задачи, initialBalance - неотрицательное число, поэтому при выполнении шагов баг-репорта тест testRateWhenNegativeBalance падает с ошибкой "Начальный баланс не может быть отрицательным, а у вас: -170"
![image](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/148256844/8ff2fe59-f350-4ce9-b4ec-a1eceeb175c7)
Для корректного расчета процентов на отрицательный остаток по счету методом yearChange была изменена формула на
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/20bd3c4007adbe0f233d6d158a6cd95d96029fbd/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L98
