### ISSUE TITLE
Не выкидывается исключение вида IllegalArgumentException, когда значение баланса счета (InitiaBalance) задается меньше минимального значения (MinBalance)

### ISSUE THREAD

**Issue by lollygolly** [ElzaRadikovna/javaqa-team-diplom#2]
**#Описание**

При создании объекта класса SavingAccount, если задаются значения параметров, где InitialBalance меньше, чем MinBalance, то в терминал НЕ выкидывается исключение вида IllegalArgumentException. 
Вместо этого в терминал выводится сообщение об ошибке: "Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown."

**#Локация дефекта**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/6258870820b32b1661549f97e91ea05e40ab3339/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

**#Шаги воспроизведения**

**1.** Открыть код программы https://github.com/ElzaRadikovna/javaqa-team-diplom/tree/main/src/main/java/ru/netology/javaqadiplom в IDEA

**2.** Сделать ассерт Assertions.assertThrows на выброс ошибки IllegalArgumentException.class при создании объекта класса SavingAccount со следующими параметрами:

- initialBalance (начальный баланс): 100,
- minBalance (минимальный баланс): 1_000,
- maxBalance (максимальный баланс): 10_000,
- rate (ставка в процентах годовых на остаток): 5

**3.** Запустить проверку теста командой mvn cleam verify в консоле IDEA

**Фактический результат:**
Тест провален с сообщением "Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown."

**Ожидаемый результат:**
Тест пройден успешно

**#Тест для проверки:**

https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/e5c5eca3b36c243ca3c102e92f9abd762dc4f1ac/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L25

**#Скриншот**

![Скриншот экрана IDEA с ошибкой в терминале](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/148256844/9e12ef85-d4cd-44f7-9822-22acd74bc767)

**#Окружение**

- Операционная система: Windows 10 22H2
- IDEA: IntelliJ IDEA Community Edition 2023.2.4
- Java: corretto-11 11.0.21

**Comment by ElzaRadikovna** [comment]
Исключение добавлено
