### ISSUE TITLE
Не увеличивается баланс при операции пополнения карты (add)

### ISSUE THREAD

**Issue by ElzaRadikovna** [ElzaRadikovna/javaqa-team-diplom#6]
# Описание
При пополнении карты на положительную сумму при начальном балансе (положительном), сумма баланса не увеличивается.
# Локация дефекта
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/c70e19b6fd5fb785c7b32a4c9e73b681ad9adaca/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65) в IDEA.
2. Создать объект класса CreditAccount 
3. Вставить значение переменной "initialBalance" (начальный баланс) в 1000руб.
4. Вставить значение переменной "creditLimit" (кредитный лимит) в  5000руб.
5. Вставить значение переменной "rate" (ставка кредитования) в 15%
6. Пополнить баланс на сумму "ammount" 3000руб. методом add
7. Использовать Assertions.assertEquals (expected 4000, actual  account.getBalance()) для сравнения результатов.

*Ожидаемый результат:* Баланс(1000) увеличился на сумму(3000) покупки: 4000
*Фактический результат:* Баланс не увеличивается: 3000

# Локация теста, для проверки метода
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/f15e823fb75896d15f5014d2c55b24755d004ee5/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L11

# Скриншот
![Скриншот 16-01-2024 231606](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/147627129/1a98a401-4ca2-4655-af6a-24c7423304a9)
# Окружение
* **Операционная система:**  Windows 10
* **IDEA:**  IntellieJ IDEA 2023.2.4 (Ultimate Edition)
* **Java:** Open JDK11

**Comment by lollygolly** [comment]
issues #6 was fixed https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/0abd2efa46e4fead340a71b5a5828943655162e7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

**Comment by lollygolly** [comment]
close issue
