### ISSUE TITLE
Отрицательный баланс при покупке (pay) на сумму, меньшей сумме начального баланса (начальный баланс положительный)

### ISSUE THREAD

**Issue by ElzaRadikovna** [ElzaRadikovna/javaqa-team-diplom#7]
# Описание
При выполнении операции  оплаты(pay) с карты, с учетом положительного начального баланса и суммы покупки, меньшей начального баланса, итоговый баланс равен отрицательной сумме покупки.
# Локация дефекта
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/6258870820b32b1661549f97e91ea05e40ab3339/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46C1-L46C1) в IDEA
2. Создать объект класса CreditAccount
3. Вставить значение переменной "initialBalance" (начальный баланс) в 4000руб.
4. Вставить значение переменной "creditLimit" (кредитный лимит) в 5000руб.
5. Вставить значение переменной "rate" (ставка кредитования) в 15%
6. Совершить покупку на сумму "ammount" 1000руб. методом pay
7. Использовать Assertions.assertEquals (expected 3000, actual account.getBalance()) для сравнения результатов.

*Ожидаемый результат:* баланс уменьшился на сумму покупки (3000)
*Фактический результат:* баланс равен отрицательной сумме покупки (-1000)

# Локация теста, для проверки метода
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/c70e19b6fd5fb785c7b32a4c9e73b681ad9adaca/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L52
# Скриншот
![Скриншот 16-01-2024 233139](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/147627129/e9afdcf9-2c39-4d93-b9d4-df1fe5452b43)

# Окружение
* **Операционная система:** Windows 10
* **IDEA:** IntellieJ IDEA 2023.2.4 (Ultimate Edition)
* **Java:** Open JDK11

**Comment by lollygolly** [comment]
issue was fixed
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/2547a53955cc62953ca9d8e4edfd5b6728d1e7c8/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L45
