### ISSUE TITLE
Кредитный лимит(CreditLimit) может быть отрицательным, отсутствует генерация исключения

### ISSUE THREAD

**Issue by ElzaRadikovna** [ElzaRadikovna/javaqa-team-diplom#8]
# Описание
При заполнении параметра CrediLimit отрицательным числом, не выкидывается исключение. Программа работает с отрицательным кредитным лимитом, что не соответствует заданным условиям.
# Локация дефекта
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/6258870820b32b1661549f97e91ea05e40ab3339/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java)
2. Создать объект класса CreditAccount
3. Вставить значение переменной "initialBalance" (начальный баланс) в 2000руб.
4. Вставить значение переменной "creditLimit" (кредитный лимит) в -5000руб.
5. Вставить значение переменной "rate" (ставка кредитования) в 20%
6. Используя метод  Assertions.assertThrows, проверить генерацию исключения.

*Ожидаемый результат:* Выкидывается исключение с сообщением "Кредитный лимит не может быть отрицательным, а у вас:"
*Фактический результат:* Программа работает с отрицательным кредитным лимитом.
# Локация теста, для проверки метода
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/c70e19b6fd5fb785c7b32a4c9e73b681ad9adaca/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L163
# Скриншот
![Скриншот 17-01-2024 142523](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/147627129/38d25aba-0200-47ea-9f4c-3e758857b8c3)

# Окружение
* Операционная система: Windows 10
* IDEA: IntellieJ IDEA 2023.2.4 (Ultimate Edition)
* Java: Open JDK11

**Comment by lollygolly** [comment]
Exception for CreditLimit was added 
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/e736147ae0b65f01a3a41936b2d9b8c4a74ca9c1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L27
