### ISSUE TITLE
Начальный баланс для счета(InitialBalance) может быть отрицательным, отсутствует генерация исключения.

### ISSUE THREAD

**Issue by ElzaRadikovna** [ElzaRadikovna/javaqa-team-diplom#9]
# Описание
При заполнении параметра InitialBalance отрицательным числом, не выкидывается исключение. Программа работает с отрицательным начальным балансом, что не соответствует заданным условиям.
# Локация дефекта
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/6258870820b32b1661549f97e91ea05e40ab3339/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java)
2. Создать объект класса CreditAccount
3. Вставить значение переменной "initialBalance" (начальный баланс) в -2000руб.
4. Вставить значение переменной "creditLimit" (кредитный лимит) в 5000руб.
5. Вставить значение переменной "rate" (ставка кредитования) в 20%
6. Используя метод  Assertions.assertThrows, проверить генерацию исключения.

*Ожидаемый результат:* Выкидывается исключение с сообщением "Начальный баланс не может быть отрицательным, а у вас:"
*Фактический результат:* Программа работает с отрицательным начальным балансом.
# Локация теста, для проверки метода
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/c70e19b6fd5fb785c7b32a4c9e73b681ad9adaca/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L169
# Скриншот
![Скриншот 17-01-2024 151303](https://github.com/ElzaRadikovna/javaqa-team-diplom/assets/147627129/83b9944b-b5a5-4737-a201-740c922c0bb3)

# Окружение
* Операционная система: Windows 10
* IDEA: IntellieJ IDEA 2023.2.4 (Ultimate Edition)
* Java: Open JDK11

**Comment by lollygolly** [comment]
Exception for initialBalance was added
https://github.com/ElzaRadikovna/javaqa-team-diplom/blob/96814f12a8af78befa5340b7bdc8fee2dd64b3a0/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L26
